title: "FirebaseとNext.jsで作るrealtime chat"
summary: "FirebaseとNext.jsを使ってリアルタイムチャットアプリを作る"
topics: ['react','firebase']
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
